### ISSUE TITLE
The NextJS client app keep asking new token key for all subsequent API call

### ISSUE THREAD

**Issue by smirfolio** [drupalninja/drupalx-decoupled#28]
I noticied that for each refreshing the nextJs client app there is some new tokens that are created 
see the <DrupalBeInstallation>/admin/config/people/simple_oauth/oauth2_token
It end up with thousand of pages of list tokens, even in NextJS build instence (Prod).
It's more effective and less stressful for the DB and the BE, if a caching token mechanism is implemented, so,for the token experiation_at period the same token will be used for all the API request call.
Here an implementation that I suggest in the  _nextjs/utils/auth.server.ts_ 

`
import { drupalAuthClient } from "drupal-auth-client";

interface TokenArgs {
  uri: string
  clientId: string
  clientSecret: string
}

let tokenCache = {
  token: null as string | null,
  expiresAt: null as string | null, // Timestamp of when the token expires
};

export const getToken = async ({uri, clientId, clientSecret}: TokenArgs) => {
  let token;
  // Check if we have a valid cached token
  if (tokenCache.token && tokenCache.expiresAt && Date.now() < parseInt(tokenCache.expiresAt)) {
    return tokenCache.token;
  } else {
    // Fetch a new token if the cached one is expired or not available
    const client = await drupalAuthClient(
      uri,
      "client_credentials",
      {
        clientId,
        clientSecret,
      }
    );
    token = `${client.token_type} ${client.access_token}`
    // Cache the token and its expiration time
    tokenCache.token = token;
    tokenCache.expiresAt = (Date.now() + parseInt( client.expires_in) * 1000).toString();
    return token;
  }
};

`
I declare  a global variable tokenCache that I check for each getToken() call to decide to ask for a new one or use the cache one.

**Important Considerations**

- Scalability: If your application scales horizontally (e.g., multiple instances of your server), each instance will have its own tokenCache. In such cases, you might want to use a shared cache like Redis.

- Stateful Deployment: Ensure that your Next.js deployment is running in a stateful manner (e.g., not serverless) to take advantage of this in-memory cache.

- Process Restart: If the server restarts (e.g., during a deployment), the cache will be cleared, and a new token will be fetched on the next API call.

**Comment by smirfolio** [comment]
@drupalninja  I will be happy if you like my implementation, to create a pull request for that

**Comment by drupalninja** [comment]
Oh wow that's nuts can you go ahead and create a PR? Thanks!

**Comment by smirfolio** [comment]
@drupalninja  Done ;)

**Comment by drupalninja** [comment]
Added this a while ago
